<?php

return [
    'roles' => [
        'admin' => ['*'],
        'user' => [
            'dashboard.view',
            'transactions.view',
            'transactions.create',
            'transactions.export',
            'transactions.correction.request',
            'receivables.view',
            'receivables.pay',
            'supplier_payables.view',
            'supplier_payables.pay',
            'reports.view',
            'reports.export',
            'settings.profile',
            'masters.customers.view',
            'masters.suppliers.view',
            'masters.suppliers.edit',
        ],
    ],

    'always_allowed' => [
        'transactions.view',
        'masters.products.view',
        'masters.customers.view',
        'masters.suppliers.view',
        'supplier_payables.view',
    ],

    'implied_permissions' => [
        'transactions.create' => [
            'sales_invoices.create',
            'sales_returns.create',
            'delivery_notes.create',
            'order_notes.create',
            'delivery_trips.create',
            'outgoing_transactions.create',
            'school_bulk_transactions.create',
            'customer_ship_locations.create',
        ],
        'transactions.edit' => [
            'sales_invoices.edit',
            'sales_returns.edit',
            'delivery_notes.edit',
            'order_notes.edit',
            'delivery_trips.edit',
            'outgoing_transactions.edit',
            'receivable_payments.edit',
            'supplier_payments.edit',
        ],
        'transactions.cancel' => [
            'sales_invoices.cancel',
            'sales_returns.cancel',
            'delivery_notes.cancel',
            'order_notes.cancel',
            'receivable_payments.cancel',
        ],
        'transactions.export' => [
            'sales_invoices.export',
            'sales_returns.export',
            'delivery_notes.export',
            'order_notes.export',
            'delivery_trips.export',
            'outgoing_transactions.export',
            'school_bulk_transactions.export',
            'receivable_payments.export',
            'supplier_payments.export',
        ],
        'masters.products.manage' => [
            'products.create',
            'products.edit',
            'products.delete',
            'products.import',
        ],
        'masters.customers.manage' => [
            'customers.create',
            'customers.edit',
            'customers.delete',
            'customers.import',
        ],
        'masters.suppliers.edit' => [
            'suppliers.create',
            'suppliers.edit',
            'suppliers.delete',
            'suppliers.import',
        ],
    ],

    'permissions' => [
        'dashboard.view',
        'transactions.view',
        'transactions.create',
        'transactions.edit',
        'transactions.export',
        'transactions.cancel',
        'transactions.correction.request',
        'transactions.correction.approve',
        'sales_invoices.create',
        'sales_invoices.edit',
        'sales_invoices.cancel',
        'sales_invoices.export',
        'sales_returns.create',
        'sales_returns.edit',
        'sales_returns.cancel',
        'sales_returns.export',
        'delivery_notes.create',
        'delivery_notes.edit',
        'delivery_notes.cancel',
        'delivery_notes.export',
        'order_notes.create',
        'order_notes.edit',
        'order_notes.cancel',
        'order_notes.export',
        'delivery_trips.create',
        'delivery_trips.edit',
        'delivery_trips.export',
        'outgoing_transactions.create',
        'outgoing_transactions.edit',
        'outgoing_transactions.export',
        'school_bulk_transactions.create',
        'school_bulk_transactions.export',
        'customer_ship_locations.create',
        'receivables.view',
        'receivables.pay',
        'receivables.adjust',
        'receivables.lock',
        'receivable_payments.edit',
        'receivable_payments.cancel',
        'receivable_payments.export',
        'supplier_payables.view',
        'supplier_payables.pay',
        'supplier_payables.adjust',
        'supplier_payments.edit',
        'supplier_payments.export',
        'reports.view',
        'reports.export',
        'settings.profile',
        'settings.admin',
        'masters.products.view',
        'masters.products.manage',
        'products.create',
        'products.edit',
        'products.delete',
        'products.import',
        'masters.customers.view',
        'masters.customers.manage',
        'customers.create',
        'customers.edit',
        'customers.delete',
        'customers.import',
        'masters.suppliers.view',
        'masters.suppliers.edit',
        'suppliers.create',
        'suppliers.edit',
        'suppliers.delete',
        'suppliers.import',
        'imports.transactions',
        'semester.bulk',
        'users.manage',
        'audit_logs.view',
    ],
];
