<?php

declare(strict_types=1);

namespace App\Support;

use App\Models\Product;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ProductDeletionService
{
    /**
     * @return array{status:string, code:string, product:?Product}
     */
    public function deleteOrDeactivate(Product $product): array
    {
        try {
            return DB::transaction(function () use ($product): array {
                $lockedProduct = Product::query()
                    ->whereKey($product->id)
                    ->lockForUpdate()
                    ->firstOrFail();

                $code = (string) ($lockedProduct->code ?? '-');

                if ($this->hasBusinessUsage((int) $lockedProduct->id)) {
                    return $this->deactivate($lockedProduct);
                }

                if (Schema::hasTable('stock_mutations') && Schema::hasColumn('stock_mutations', 'product_id')) {
                    DB::table('stock_mutations')
                        ->where('product_id', (int) $lockedProduct->id)
                        ->delete();
                }

                $lockedProduct->delete();

                return [
                    'status' => 'deleted',
                    'code' => $code,
                    'product' => null,
                ];
            });
        } catch (QueryException $exception) {
            if (! $this->isDeleteBlockedByRelation($exception)) {
                throw $exception;
            }

            return DB::transaction(function () use ($product): array {
                $lockedProduct = Product::query()
                    ->whereKey($product->id)
                    ->lockForUpdate()
                    ->firstOrFail();

                return $this->deactivate($lockedProduct);
            });
        }
    }

    private function hasBusinessUsage(int $productId): bool
    {
        foreach ($this->businessUsageTables() as $table) {
            if (! Schema::hasTable($table) || ! Schema::hasColumn($table, 'product_id')) {
                continue;
            }

            if (DB::table($table)->where('product_id', $productId)->exists()) {
                return true;
            }
        }

        return false;
    }

    /**
     * Stock mutations are intentionally excluded: they are bookkeeping rows
     * generated by product creation/manual stock edits, not business documents.
     *
     * @return list<string>
     */
    private function businessUsageTables(): array
    {
        return [
            'sales_invoice_items',
            'sales_return_items',
            'outgoing_transaction_items',
            'delivery_note_items',
            'order_note_items',
            'school_bulk_transaction_items',
        ];
    }

    /**
     * @return array{status:string, code:string, product:?Product}
     */
    private function deactivate(Product $product): array
    {
        $code = (string) ($product->code ?? '-');
        $product->update(['is_active' => false]);

        return [
            'status' => 'deactivated',
            'code' => $code,
            'product' => $product->fresh(),
        ];
    }

    private function isDeleteBlockedByRelation(QueryException $exception): bool
    {
        $sqlState = (string) $exception->getCode();
        $driverCode = (int) ($exception->errorInfo[1] ?? 0);

        return in_array($sqlState, ['23000', '23503'], true)
            || in_array($driverCode, [1451, 1452], true);
    }
}
